package:
    name: libint
    version: 2.0.3 
source:
    fn: libint-2.0.3-stable.tgz 
    url: http://downloads.sourceforge.net/project/libint/libint-for-mpqc/libint-2.0.3-stable.tgz 
build:
    number: 2 
    run_exports:
      - libint 
requirements:
    build:
      - {{ compiler('c') }}
      - {{ compiler('cxx') }}
      - autoconf
      - ccache
    host:
      - gmp
      - boost
    run: []
test:
    commands:
      - conda inspect linkages libint
about:
    home: https://github.com/psi4/libint
    license: GPL2 
    summary: two-body molecular integrals over Gaussian functions library
